### ISSUE TITLE
Add "Testing needed" mechanism to the website

### ISSUE THREAD

**Issue by abaire** [mborgerson/xemu-website#83]
In order to better organize testers, we should have a section on the website that lists issues and/or titles that specifically need attention.

Features:

A mechanism to automatically set priority/sort order. 

- Titles with recently closed issues (since the xemu version in the last compatibility report) should be boosted so that fixes can be verified. 
- Titles with recently reported issues should be boosted so that issues can be verified (but prioritized lower than recently closed). 
- Remaining titles should be prioritized by age of last compatibility report (oldest reports first) to encourage re-tests.
- The automatic boosts should be ignored once a new compatibility report comes in.

Ideally privileged users should also have a mechanism to override the automatic priority.

It'd also be nice to have a mechanism for privileged users to add specific notes (e.g., "Please test this on Windows with an AMD card.")

**Comment by mborgerson** [comment]
Mostly done now, with the list at https://xemu.app/testing_priority.html. Additional priorities can be added in the future with issue labels.
